spring.application.name=PROOF Importer
spring.main.lazy-initialization=false
spring.main.log-startup-info=false
spring.output.ansi.enabled=ALWAYS

#Elastic
#spring.elasticsearch.uris=https://proof2-elastic-jt.cloud.iai.kit.edu:443

spring.application.version=@project.version@
spring.application.buildAt=@maven.build.timestamp@

spring.datasource.url=jdbc:postgresql://localhost:5432/proof
spring.datasource.username=admin
spring.datasource.password=admin
spring.main.allow-bean-definition-overriding=true

spring.datasource.driver-class-name=org.postgresql.Driver