#!/bin/bash
#
# bash script that empties a PROOF postgres database in a docker container called 'proof-postgres'
#
clearFile=/tmp/emptyDatabase

echo  "truncate attachment  CASCADE;
truncate step_based_config  CASCADE;
truncate step_size_definition CASCADE;
truncate program CASCADE;
truncate template CASCADE;
truncate program_attached CASCADE;
truncate applied_inputs CASCADE;
truncate block  CASCADE;
truncate connection CASCADE;" > /tmp/emptyDatabase
#cat $clearFile

docker cp $clearFile proof-postgres:$clearFile && docker exec proof-postgres sh -c "psql --username=admin proof < $clearFile"

