#!/bin/bash
#
# bash script that creates a PROOF postgres database dump from a docker container called 'proof-postgres'
#
pathAndFileName=$(date +%Y_%m_%d_)proof-postgres-db-dump.sql
if [ "$1" != "" ]; then
    pathAndFileName=$1
fi

docker exec proof-postgres sh -c "pg_dump -U admin --data-only --column-inserts --dbname=proof > /tmp/db-dump.sql" && docker cp proof-postgres:/tmp/db-dump.sql "$pathAndFileName"

